version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: colibris-db
    ports:
      - "5432:5432"
    volumes:
      - colibris-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always

  colibris:
    image: colibris
    container_name: colibris-web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c "
      python manage.py migrate --no-input &&
      python manage.py insert_employee_data ./.docker/db/MOCK_DATA.json &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/colibris
    depends_on:
      - db
    restart: unless-stopped


volumes:
    colibris-pgdata:
